version: "3"
services:
  wrkchain_bootnode:
    hostname: wrkchain_bootnode
    build:
      context: ./Docker
      dockerfile: ./bootnode/Dockerfile
    ports:
    - ${BOOTNODE_PORT}:${BOOTNODE_PORT}/udp
    environment:
    - BOOTNODE_PORT=${BOOTNODE_PORT}

  wrkchain_validator_1:
    hostname: wrkchain_validator_1
    depends_on:
    - wrkchain_bootnode
    environment:
    - PUBLIC_ADDRESS=${EV1_PUBLIC_ADDRESS}
    - BOOTNODE_ID=${BOOTNODE_ID}
    - BOOTNODE_IP=${BOOTNODE_IP}
    - BOOTNODE_PORT=${BOOTNODE_PORT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}
    - GETH_LISTEN_PORT=${WRKCHAIN_EV1_GETH_LISTEN_PORT}
    build:
      context: ./Docker
      dockerfile: ./validator/Dockerfile
      args:
        PRIVATE_KEY: ${EV1_PRIVATE_KEY}
        WALLET_PASS: ${EV1_WALLET_PASS}
        GENESIS_JSON_FILENAME: ${WRKCHAIN_GENESIS_JSON_FILENAME}
    container_name: wrkchain_validator_1
    ports:
    - ${WRKCHAIN_EV1_GETH_LISTEN_PORT}:${WRKCHAIN_EV1_GETH_LISTEN_PORT}/udp

  wrkchain_validator_2:
    hostname: wrkchain_validator_2
    depends_on:
    - wrkchain_bootnode
    environment:
    - PUBLIC_ADDRESS=${EV2_PUBLIC_ADDRESS}
    - BOOTNODE_ID=${BOOTNODE_ID}
    - BOOTNODE_IP=${BOOTNODE_IP}
    - BOOTNODE_PORT=${BOOTNODE_PORT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}
    - GETH_LISTEN_PORT=${WRKCHAIN_EV2_GETH_LISTEN_PORT}
    build:
      context: ./Docker
      dockerfile: ./validator/Dockerfile
      args:
        PRIVATE_KEY: ${EV2_PRIVATE_KEY}
        WALLET_PASS: ${EV2_WALLET_PASS}
        GENESIS_JSON_FILENAME: ${WRKCHAIN_GENESIS_JSON_FILENAME}
    container_name: wrkchain_validator_2
    ports:
    - ${WRKCHAIN_EV2_GETH_LISTEN_PORT}:${WRKCHAIN_EV2_GETH_LISTEN_PORT}/udp

  wrkchain_node_1:
    hostname: wrkchain_node_1
    depends_on:
    - wrkchain_validator_1
    environment:
    - BOOTNODE_ID=${BOOTNODE_ID}
    - BOOTNODE_IP=${BOOTNODE_IP}
    - BOOTNODE_PORT=${BOOTNODE_PORT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}
    - GETH_LISTEN_PORT=${WRKCHAIN_RPC_NODE_GETH_LISTEN_PORT}
    - RPC_PORT=${WRKCHAIN_RPC_PORT}
    build:
      context: ./Docker
      dockerfile: ./node/Dockerfile
      args:
        PRIVATE_KEY: ${RPC_NODE_PRIVATE_KEY}
        WALLET_PASS: ${RPC_NODE_WALLET_PASS}
        GENESIS_JSON_FILENAME: ${WRKCHAIN_GENESIS_JSON_FILENAME}
    container_name: wrkchain_node_1
    ports:
    - ${WRKCHAIN_RPC_PORT}:${WRKCHAIN_RPC_PORT}

  wrkchain_explorer:
    hostname: wrkchain_explorer
    depends_on:
    - wrkchain_node_1
    ports:
    - ${WRKCHAIN_EXPLORER_PORT}:${WRKCHAIN_EXPLORER_PORT}
    environment:
    - WRKCHAIN_EXPLORER_PORT=${WRKCHAIN_EXPLORER_PORT}
    build:
      context: ./Docker
      dockerfile: ./explorer/Dockerfile
      args:
        WRKCHAIN_EXPLORER_PORT: ${WRKCHAIN_EXPLORER_PORT}
        WRKCHAIN_RPC_PORT: ${WRKCHAIN_RPC_PORT}
        COIN_SYM: ${WRKCHAIN_COIN_SYM}
        WRKCHAIN_NAME: ${WRKCHAIN_NAME}

    container_name: wrkchain_explorer

  wrkchain_validator_service:
    hostname: wrkchain_validator_service
    depends_on:
      - wrkchain_node_1
    build:
      context: ./Docker
      dockerfile: Docker/wrkchain_validator_service/Dockerfile
    ports:
    - ${WRKCHAIN_VALIDATOR_SERVICE_PORT}:${WRKCHAIN_VALIDATOR_SERVICE_PORT}
    container_name: wrkchain_validator_service

  wrkchain_oracle:
    hostname: wrkchain_oracle
    depends_on:
      - wrkchain_validator_service
    build:
      context: ./Docker
      dockerfile: ./wrkchain_oracle/Dockerfile
    container_name: wrkchain_oracle
    environment:
    - MAINCHAIN_WEB3_PROVIDER_URL=${MAINCHAIN_WEB3_PROVIDER_URL}
    - WRKCHAIN_WEB3_PROVIDER_URL=${WRKCHAIN_WEB3_PROVIDER_URL}
    - PRIVATE_KEY=${EV1_PRIVATE_KEY}
    - WRKCHAIN_ROOT_CONTRACT_ADDRESS=${WRKCHAIN_ROOT_CONTRACT_ADDRESS}
    - WRKCHAIN_ROOT_WRITE_TIMEOUT=${WRKCHAIN_ROOT_WRITE_TIMEOUT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}

