---
# Custom BASH Helpers

- name: .bashrc
  template: src=.bashrc dest=/home/deploy/.bashrc owner=deploy group=deploy
  become: yes

- name: motd
  template: src=motd dest=/etc/motd owner=root group=root
  become: yes

...
