---
- hosts: {{ name }}
  gather_facts: no

  roles:
    - base
    - ethereum
    - bootnode

  tasks:
    - hostname: name={{ name }}
      become: yes

    - name: upgrade all packages
      yum: name=* state=latest
      become: yes

...
