---
# base role

- name: enable EPEL
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  become: yes

- name: upgrade all packages
  yum: name=* state=latest
  become: yes

- name: install yum dependencies
  yum:
    name:
      - git
      - nc
      - mosh
      - telnet
      - tmux
      - wget
      - vim
    state: latest
  become: yes

- name: Ensure group deploy exists
  group:
    name: deploy
    state: present
  become: yes

- name: Add the user 'deploy'
  user:
    name: deploy
    comment: The Deployment User
    groups: deploy
  become: yes

- name: ssh key for the root user
  authorized_key: user=root key="{{ lookup('file', 'id_rsa_root.pub') }}"
  become: yes

- name: ssh key for the deploy user
  authorized_key: user=deploy key="{{ lookup('file', 'id_rsa_deploy.pub') }}"
  become: yes

...
