---
# Custom BASH Helpers

- name: .bashrc
  copy: src=.bashrc dest=/home/{{ ansible_user }}/.bashrc owner={{ ansible_user }} group={{ ansible_user }}

- name: motd
  copy: src=motd dest=/etc/motd owner=root group=root
  become: yes

...
