---
# Services for each Node

- name: install wrkchain service
  template:
    src: wrkchain.service
    dest: /etc/systemd/system/wrkchain.service
    mode: "0755"
  become: yes

- name: enable systemd services
  systemd:
    name: wrkchain.service
    enabled: yes
  become: yes

- name: reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Allow user deploy to start wrkchain
  lineinfile:
    path: /etc/sudoers.d/deploy
    line: 'deploy ALL=(ALL) NOPASSWD: /usr/bin/systemctl start wrkchain.service'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: Allow user deploy to stop wrkchain
  lineinfile:
    path: /etc/sudoers.d/deploy
    line: 'deploy ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop wrkchain.service'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: Allow user deploy to restart wrkchain
  lineinfile:
    path: /etc/sudoers.d/deploy
    line: 'deploy ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart wrkchain.service'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  become: yes

...
