---
# Install geth

- name: install yum dependencies
  yum:
    name:
      - gcc
      - make
    state: latest
  become: yes

- name: Download Go
  get_url:
    url: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    dest: /home/{{ home }}/go.tar.gz
    owner: {{ home }}
    group: {{ home }}

- name: Extract go.tar.gz into /usr/local
  unarchive:
    src: /home/{{ home }}/go.tar.gz
    dest: /usr/local
    remote_src: yes

- name: create local go directory
  file: path=/home/{{ home }}/.go state=directory owner={{ home }} group={{ home }}

- command: /usr/local/go/bin/go get -d github.com/ethereum/go-ethereum
  args:
    chdir: /home/{{ home }}
    creates: /home/{{ home }}/.go/src/github.com/ethereum/go-ethereum

- command: /usr/local/go/bin/go get github.com/ethereum/go-ethereum/cmd/geth
  args:
    chdir: /home/{{ home }}
    creates: /home/{{ home }}/.go/bin/geth

- name: create data directories
  file: path=/home/{{ home }}/data state=directory owner={{ home }} group={{ home }}

...
