---
# Install Go Ethereum

- name: install yum dependencies
  yum:
    name:
      - gcc
      - make
    state: latest
  become: yes

- name: Download and unpack Go
  unarchive:
    src: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes

- name: create ethereum go directory
  file: path=/home/{{ ansible_user }}/.go/src/github.com/ethereum state=directory owner={{ ansible_user }} group={{ ansible_user }} recurse=yes

- command: git clone https://github.com/ethereum/go-ethereum --depth 1
  args:
    chdir: /home/{{ ansible_user }}/.go/src/github.com/ethereum
    creates: /home/{{ ansible_user }}/.go/src/github.com/ethereum/go-ethereum

- command: /usr/local/go/bin/go install github.com/ethereum/go-ethereum/cmd/geth
  args:
    chdir: /home/{{ ansible_user }}
    creates: /home/{{ ansible_user }}/.go/bin/geth
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/{{ ansible_user }}/.go

- command: /usr/local/go/bin/go install github.com/ethereum/go-ethereum/cmd/bootnode
  args:
    chdir: /home/{{ ansible_user }}
    creates: /home/{{ ansible_user }}/.go/bin/bootnode
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/{{ ansible_user }}/.go

- name: create data directories
  file: path=/home/{{ ansible_user }}/.ethereum state=directory owner={{ ansible_user }} group={{ ansible_user }}
...
