---
# Install geth

- name: install yum dependencies
  yum:
    name:
      - gcc
      - make
    state: latest
  become: yes

- name: Download Go
  get_url:
    url: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    dest: /home/{{ home }}/go.tar.gz
    owner: {{ home }}
    group: {{ home }}

- name: Extract go.tar.gz into /usr/local
  unarchive:
    src: /home/{{ home }}/go.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes

- name: create ethereum go directory
  file: path=/home/{{ home }}/.go/src/github.com/ethereum state=directory owner={{ home }} group={{ home }} recurse=yes

- command: git clone https://github.com/ethereum/go-ethereum --depth 1
  args:
    chdir: /home/{{ home }}/.go/src/github.com/ethereum
    creates: /home/{{ home }}/.go/src/github.com/ethereum/go-ethereum

- command: /usr/local/go/bin/go install github.com/ethereum/go-ethereum/cmd/geth
  args:
    chdir: /home/{{ home }}
    creates: /home/{{ home }}/.go/bin/geth
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/{{ home }}/.go

- command: /usr/local/go/bin/go install github.com/ethereum/go-ethereum/cmd/bootnode
  args:
    chdir: /home/{{ home }}
    creates: /home/{{ home }}/.go/bin/bootnode
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/{{ home }}/.go

- name: create data directories
  file: path=/home/{{ home }}/data state=directory owner={{ home }} group={{ home }}

...
