---
# Account imports

- name: create node_keys directory
  file: path=/home/deploy/{{ wrkchain_data_dir }}/node_keys state=directory owner=deploy group=deploy recurse=yes

- name: Copy Genesis File
  copy: src=genesis.json dest=/home/deploy/{{ wrkchain_data_dir }}/genesis.json owner=deploy group=deploy

- name: Initialize the genesis file
  command: /home/deploy/.go/bin/geth --datadir=/home/deploy/{{ wrkchain_data_dir }} init /home/deploy/{{ wrkchain_data_dir }}/genesis.json
  args:
    creates: /home/deploy/{{ wrkchain_data_dir }}/geth/chaindata

- name: Write the privatekey
  copy: content="{{ private_key }}" dest=/home/deploy/.privatekey
  no_log: true

- name: Write the password file
  copy: content="{{ password }}" dest=/home/deploy/.walletpassword
  no_log: true

- name: Import the account
  command: /home/deploy/.go/bin/geth --datadir=/home/deploy/{{ wrkchain_data_dir }} account import --password /home/deploy/.walletpassword /home/deploy/.privatekey

- name: Delete the privatekey
  file:
    state: absent
    path: /home/deploy/.privatekey

- name: Delete the password file
  file:
    state: absent
    path: /home/deploy/.walletpassword

...
