---
# Node Role

- command: /usr/local/go/bin/go install github.com/ethereum/go-ethereum/cmd/geth
  args:
    chdir: /home/{{ ansible_user }}
    creates: /home/{{ ansible_user }}/.go/bin/geth
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/{{ ansible_user }}/.go

- stat:
    path: /home/{{ ansible_user }}/.ethereum/geth/chaindata/CURRENT
  register: st

- name: Import accounts
  include: account.yml
  when: not st.stat.exists

...
