---
# Node Role

- command: /usr/local/go/bin/go install github.com/ethereum/go-ethereum/cmd/geth
  args:
    chdir: /home/deploy
    creates: /home/deploy/.go/bin/geth
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/deploy/.go
  become: yes
  become_user: deploy

- stat:
    path: /home/deploy/{{ wrkchain_data_dir }}/geth/chaindata/CURRENT
  register: st
  become: yes

- name: Import accounts
  include: account.yml
  when: not st.stat.exists
  become: yes
  become_user: deploy

- name: install geth service
  template:
    src: geth.service
    dest: /etc/systemd/system/geth.service
    mode: "0755"
  become: yes

- name: enable systemd services
  systemd:
    name: geth.service
    enabled: yes
  become: yes

- name: reload systemd
  command: systemctl daemon-reload
  become: yes

...
